# Generated by Django 5.2 on 2025-04-24 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_country_asset_current_balance_user_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.country'),
        ),
        migrations.AddField(
            model_name='stage',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.district'),
        ),
        migrations.AddField(
            model_name='stage',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
    ]
