# Generated by Django 5.0 on 2025-04-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_district_region_alter_region_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(default='Unnamed Asset', max_length=100),
        ),
    ]
