# Generated by Django 5.0 on 2025-04-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_asset_asset_id_alter_asset_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_id',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='name',
        ),
    ]
