# Generated by Django 5.0 on 2025-04-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_asset_asset_id_remove_asset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
