# Generated by Django 5.0 on 2025-04-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_asset_asset_id_asset_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='value',
            new_name='base_value',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='method',
            new_name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='asset',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='selling_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now_add=True, default="2025-01-01"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(max_length=50),
        ),
    ]
