# Generated by Django 5.0 on 2025-04-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_value_asset_base_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
