# Generated by Django 5.2 on 2025-04-26 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_asset_is_deleted_payment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='core.assetrequest'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
