# Generated by Django 5.2 on 2025-04-26 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_asset_request_assetrequest_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('field_agent', 'Field Agent'), ('user', 'User')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='chairman',
            field=models.ForeignKey(limit_choices_to={'role': 'user'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
