# Generated by Django 5.2 on 2025-04-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_role_alter_assetrequest_chairman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='request',
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(default='unassigned', max_length=20),
        ),
        migrations.DeleteModel(
            name='AssetRequest',
        ),
    ]
