# Generated by Django 5.0 on 2025-04-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_asset_request_alter_asset_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('paid', 'Paid')], default='unassigned', max_length=20),
        ),
    ]
